spring.application.name=Restaurant
server.port=9090
server.address=0.0.0.0

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/booking_restaurant?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tinhthanh387@gmail.com
spring.mail.password=gjxu ezdh grmf mqdp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

vnpay.tmn-code=5BGIHZA0
vnpay.hash-secret=KGH6Y1C6OPMU14ZKUR0FHP0D1OKWMYEY
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=https://sueann-indistinct-easter.ngrok-free.dev/api/payment/vnpay-return
vnpay.ipn-url=https://sueann-indistinct-easter.ngrok-free.dev/api/payment/vnpay-ipn
vnpay.version=2.1.0
server.forward-headers-strategy=framework
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for

openai.api.key=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
openai.model=gpt-4.1-mini

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=909902503440-2gr2o98nvsngpoduehbbab7ad2uffvmh.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# n?i l?u file upload
app.upload-dir=uploads

# gi?i h?n upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

server.error.include-message=always

# Google Gemini API
gemini.api.key=AIzaSyAhH4fDowkDG2FyR_CqhtPIaX3pop8WQRY
gemini.text.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=
gemini.vision.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=
gemini.mock.enabled=false

app.review.guest-cutoff=2026-05-06T00:00:00

